### ISSUE TITLE
Fail early instead of warn when Secret Server login fails

### ISSUE THREAD

**Issue by salsburj** [imsweb/cconf#2]
If you try using an incorrect password to a Secret Server Account and then you try retrieving a secret named `some_secret` via the API, the following will happen:
```
ConfigWarning: PZIP_STORAGE_KEY: Login failed.
...
KeyError: '`some_secret` not found in any of: SecretServerSource'
```
It's redacted in the example above, but there's a lot of content in the stacktrace between the `ConfigWarning` and the `KeyError`, so it's very easy to miss the `ConfigWarning` that's at the top.

When a developer sees the `KeyError` only, it gives the impression that the API account doesn't have permission to view `some_secret`. However, what actually may be happening is that the API account _does_ have permission to view `some_secret`, but retrieval is failing since the login failed. If login fails, that should raise an error and terminate the program, not send a warning and continue processing.

**Comment by dcwatson** [comment]
I added a `verify` option to the `SecretServerSource`, which will try to run an authenticated call immediately, so it will fail fast. Will get this out soon.
