### ISSUE TITLE
Use os.path.expandvars for EnvFile file path

### ISSUE THREAD

**Issue by ewohnlich** [imsweb/cconf#3]
In EnvFile when you safe_open self._env_file can we use os.path.expandvars? So:

    with safe_open(os.path.expandvars(self._env_file), policy=self._policy) as fileobj

My app needs to know the location of the env/key files in its conf file. Something like this snippet:

```
host localhost
debug-mode on
<environment>
    CCONF_ENV_FILE %UserProfile%/.cconf/.env
    CCONF_ENV_FILE %UserProfile%/.cconf/.plone.key
```

This would let me use the same template file for all windows users, and instruct them to create the key and env file in their home directory. But without expandvars it's just going to read that literally.

**Comment by dcwatson** [comment]
`CCONF_ENV_FILE` isn't part of `cconf`, is that part of your code? Is there some reason you can't call `os.path.expandvars` on it when reading it from the environment? I'm not necessarily opposed, but unless we add ways to configure sources from the environment, I don't see this as super necessary.

**Comment by ewohnlich** [comment]
Yes that is in my code. I might be able to expand it on my end before sending it to cconf now that I think about it.

**Comment by ewohnlich** [comment]
I was able to do it there, closing.
